In [1]:
# الخلية 1: استيراد المكتبات وتحميل البيانات
from sklearn.datasets import fetch_california_housing
import pandas as pd

# تحميل بيانات كاليفورنيا
california = fetch_california_housing()
X = california.data  # الميزات
y = california.target  # الأسعار

# تحويل البيانات إلى DataFrame لتسهيل التعامل معها
df = pd.DataFrame(X, columns=california.feature_names)
df['MedHouseVal'] = y  # إضافة الأسعار إلى DataFrame


In [2]:
# الخلية 2: تحويل الهدف إلى فئات
from sklearn.preprocessing import KBinsDiscretizer

# تحويل الهدف (MedHouseVal) إلى فئات
k_bins = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
y_binned = k_bins.fit_transform(y.reshape(-1, 1)).ravel()


C:\Users\Nescafe\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:239: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


In [3]:
# الخلية 3: تقسيم البيانات إلى تدريب واختبار
from sklearn.model_selection import train_test_split

# تقسيم البيانات إلى مجموعة تدريب ومجموعة اختبار مع 20% فقط
X_train_nb, X_test_nb, y_train_nb, y_test_nb = train_test_split(X, y_binned, test_size=0.2, random_state=42)


In [4]:
# الخلية 4: إنشاء نموذج Naive Bayes
from sklearn.naive_bayes import GaussianNB

# إنشاء نموذج Naive Bayes
nb_model = GaussianNB()
nb_model.fit(X_train_nb, y_train_nb)  # تدريب النموذج


GaussianNB()

In [6]:
# الخلية 5: التنبؤ وعرض النتائج
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# التنبؤ باستخدام مجموعة الاختبار
y_pred_nb = nb_model.predict(X_test_nb)

# حساب الدقة
accuracy_nb = (y_pred_nb == y_test_nb).mean()
print(f"Naive Bayes Accuracy: {accuracy_nb:.2f}")

# عرض مصفوفة الارتباك
print("Confusion Matrix:")
print(confusion_matrix(y_test_nb, y_pred_nb))

# عرض تقرير التصنيف
print("Classification Report:")
print(classification_report(y_test_nb, y_pred_nb))


Naive Bayes Accuracy: 0.44
Confusion Matrix:
[[ 215 1795   21]
 [  20 1480   18]
 [   7  445  127]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.89      0.11      0.19      2031
         1.0       0.40      0.97      0.57      1518
         2.0       0.77      0.22      0.34       579

    accuracy                           0.44      4128
   macro avg       0.68      0.43      0.37      4128
weighted avg       0.69      0.44      0.35      4128

