In [8]:
# الخلية 1: استيراد المكتبات وتحميل البيانات
from sklearn.datasets import fetch_california_housing
import pandas as pd

# تحميل بيانات كاليفورنيا
california = fetch_california_housing()
X = california.data  # الميزات
y = california.target  # الأسعار

# تحويل البيانات إلى DataFrame لتسهيل التعامل معها
df = pd.DataFrame(X, columns=california.feature_names)
df['MedHouseVal'] = y  # إضافة الأسعار إلى DataFrame


In [9]:
# الخلية 2: تحويل الهدف إلى فئات
from sklearn.preprocessing import KBinsDiscretizer

# تحويل الهدف (MedHouseVal) إلى فئات
k_bins = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
y_binned = k_bins.fit_transform(y.reshape(-1, 1)).ravel()


C:\Users\Nescafe\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:239: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


In [10]:
# الخلية 3: تقسيم البيانات إلى تدريب واختبار
from sklearn.model_selection import train_test_split

# تقسيم البيانات إلى مجموعة تدريب ومجموعة اختبار مع 20% فقط
X_train_svc, X_test_svc, y_train_svc, y_test_svc = train_test_split(X, y_binned, test_size=0.2, random_state=42)


In [11]:
# الخلية 4: إنشاء نموذج SVC
from sklearn.svm import SVC

# إنشاء نموذج SVC
svc_model = SVC(random_state=42)
svc_model.fit(X_train_svc, y_train_svc)  # تدريب النموذج


SVC(random_state=42)

In [13]:
# الخلية 5: التنبؤ وعرض النتائج
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# التنبؤ باستخدام مجموعة الاختبار
y_pred_svc = svc_model.predict(X_test_svc)

# حساب الدقة
accuracy_svc = (y_pred_svc == y_test_svc).mean()
print(f"SVC Accuracy: {accuracy_svc:.2f}")

print("Confusion Matrix:")
print(confusion_matrix(y_test_svc, y_pred_svc))

# عرض تقرير التصنيف
print("Classification Report:")
print(classification_report(y_test_svc, y_pred_svc))

SVC Accuracy: 0.49
Confusion Matrix:
[[2021   10    0]
 [1507   11    0]
 [ 575    4    0]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.49      1.00      0.66      2031
         1.0       0.44      0.01      0.01      1518
         2.0       0.00      0.00      0.00       579

    accuracy                           0.49      4128
   macro avg       0.31      0.33      0.22      4128
weighted avg       0.40      0.49      0.33      4128



C:\Users\Nescafe\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nescafe\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nescafe\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
